### ISSUE TITLE
Duplicate carriers/shipping method gets displayed when multiple association are available in the database

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/fulfillment#883]
## Current behavior

If the same shipping method gets associated with a carrier multiple times, then in that case, the shipping method is displayed multiple times in the dropdown on the order details page or in the tracking code modal.

## Expected behavior

If the carrier or shipping methods have multiple associations then only unique values should be displayed in the all the select dropdowns.

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version: 

## Additional information

![image](https://github.com/user-attachments/assets/2ddf9e1e-edea-4ff3-8e6a-1242ac4a7a90)

**Comment by ravilodhi** [comment]
The duplicate carriers are caused by duplicate data in the FacilityParty table, and the duplicate shipment methods are due to duplicate data in the ProductStoreShipmentMeth table. The source of the duplicate data should be fixed to resolve this issue correctly. As a precaution, a PR has been raised to fetch distinct records.

**Comment by Adameddy26** [comment]
Verified and working fine in release v2.13.0. Hence, closing this issue.
